### ISSUE TITLE
"make info" command fails

### ISSUE THREAD

**Issue by stevevance** [fitnr/osm-tiny-maps#1]
I've set up everything according to your instructions, I believe. 

I have a `bounds.json` file with valid JSON, for an area surrounding the Chicago Loop. 

```
{
    "chicago-loop": {
        "minx": -87.71896362304688,
        "miny": 41.832735062152615,
        "maxx": -87.56927490234375,
        "maxy": 41.92578147109541
    }
}
```

I have a `query.ql` file with an Overpass Turbo query that I [executed on that site](http://overpass-turbo.eu/s/eF3).

```
[out:xml][timeout:25];
// gather results
(

  way["highway"="primary"]({{bbox}});
   way["highway"="secondary"]({{bbox}});

);
// print results
out meta;
>;
out meta qt;
```

And my `config.ini` file is set up. 

```
# json boundaries json file
BOUNDSFILE = bounds.json

# template for querying the Overpass API
QUERYFILE = query.ql
```

All files are in the same directory as `Makefile`. 
I ran `make info` and I got this error:

```
parse error: Invalid numeric literal at line 1, column 5
parse error: Invalid numeric literal at line 1, column 5
Makefile:108: *** multiple target patterns.  Stop.
```

**Comment by fitnr** [comment]
The problem was in the JQ pattern for getting the bounds - it was unquoted, so it interpreted the `-` in `chicago-loop` as a minus sign. I've added quotes, which will allow arbitrary keys.

**Comment by stevevance** [comment]
I pulled your latest changes, but this error is still happening:
`Makefile:108: *** multiple target patterns.  Stop.`

**Comment by fitnr** [comment]
Hmm. What's your platform and version of `make`?

**Comment by stevevance** [comment]
GNU Make 3.81
This program built for i386-apple-darwin11.3.0
Mac OS X 10.11.3

**Comment by stevevance** [comment]
I just by chance pulled your latest changes since my previous comment about my machine build and it generated exactly what I asked for!

![chicago-loop](https://cloud.githubusercontent.com/assets/1330459/13377173/fc2fd170-dd95-11e5-8c24-2b599638df22.png)

Now my question is, I have all of these GeoJSON files representing each of the 50 Chicago wards. How can I tell `osm-tiny-maps` to convert those to its required `bounds` format?

**Comment by fitnr** [comment]
You can use the `svgis bounds` command to generate a bounds for each ward. I would put this into a CSV and check it into git (`26,x y X Y`)

It will probably be quicker to download OSM data for the entire Chicago area, then use the bounds for each ward as an option (`svgis draw --bounds x y X Y`). The task in this repo that generates .ql files shows how to do this, it can be adapted for the SVG-creation step.

**Comment by fitnr** [comment]
I don't know why I suggested something complicated. The best way to use the bounds from a file is with a pipe and `xargs`, like this:

``` make
ward-%.svg: ward-%.json chicago_osm.shp
      svgis bounds $< | xargs -I {} svgis draw $^ -o $@ --bounds {}

chicago_osm.shp: chicago.osm
      [copy the osm to shp conversion from this repo]
```

**Comment by stevevance** [comment]
"I don't know why I suggested something complicated."

You might have a "bits and pieces" understanding of what I'm trying to do with these packages. I started articulating it in a note-to-self over the weekend, but I haven't finished.

**Comment by fitnr** [comment]
:+1:, figuring out your own projects is the fun and hard part

FYI, since we started this thread, I've changed the Makefile to only use geojson, since they have the benefit of being readable in a text editor.
